KindleGalleryPusher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainsite.views import home_page, volume_download, show_bandwidth_rule, feedback
from ebookconvert.views import convert_queue
from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.urls import include, path  # For django versions from 2.0 and up

urlpatterns = [
                  path("", home_page, name='home_page'),
                  path('rule/', show_bandwidth_rule, name='bandwidth_rule'),
                  path("book/", include("mainsite.urls")),
                  path("feedback/", feedback, name='feedback'),
                  path("download/", volume_download, name='volume_download'),
                  path('accounts/', include('account.urls')),
                  path('search/', include('mainsite.urls_search')),
                  path('pushtask/', include('pushmonitor.urls')),
                  path('converts/', convert_queue, name='convert_queue'),
                  path('admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('login/', views.account_login, name='login'),
    path('register/', views.account_register, name='register'),
    path('forgot/', views.account_reset_password, name='forgot'),
    path('resetpsw/', views.rest_password, name='reset_password'),
    path('active/', views.account_activate, name='active'),
    path('logout/', views.account_logout, name='logout'),
    path('user/', views.set_self_account, name='self_profile'),
    path('user/profile', views.set_profile, name='set_profile'),
    path('user/<int:uid>/', views.account_profile, name='other_profile'),
    path('user/queue/', views.push_queue, name='push_queue'),
    path('charge/', views.kakin, name='charge'),
    path('payoknDxx4S0qCf/', views.payok, name='pay_ok'),
    path('precharge/', views.precharge, name='precharge'),
    path('records/', views.bandwidth_cost_records, name='bandwidth_records'),
    path('collections/', views.full_collection, name='collections'),
    path('subscs/', views.full_subscs, name='subscs'),

]

account/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpRequest, HttpResponseRedirect
from django.utils import timezone

from django.views.decorators.csrf import csrf_exempt

from account.models import User, MailVertifySendRecord, PasswordResetMailSendRecord, ChargeRecord, CHARGE_MODE_VIP, \
    AccountRegisterIpRecord, get_unique_invite_code, USER_BASE_BANDWIDTH, INVITED_USER_BASE_BANDWIDTH
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from mainsite.models import ImageWithThumb
from django.core.files import File
from django.core.validators import validate_email, ValidationError
from pushmonitor.models import get_user_push_task_from_queue, get_global_push_tasks_from_queue, get_random_string
from django.conf import settings

def account_login(request: HttpRequest):
    if request.method == 'GET':
        redirect_path = request.GET.get("next")
        if redirect_path == "": redirect_path = None
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('main_site:home_page'))
        return render(request, 'accounts/login.html', context={"redirect_path": redirect_path})
    elif request.method == 'POST':
        user_name = request.POST['username']
        password = request.POST['password']
        try:
            validate_email(user_name)
            users = User.objects.filter(email=user_name)
            if len(users) == 0:
                return HttpResponse("Login Failed. Error username or password!", status=401)
            else:
                user = authenticate(request, username=users[0].username, password=password)
        except ValidationError:
            user = authenticate(request, username=user_name, password=password)
        if user is not None:
            login_res = login(request, user)
            print("login res", login_res)
            return HttpResponse("login success")
        else:
            return HttpResponse("Login Failed. Error username or password!", status=401)
    else:
        raise Http404


def account_activate(request):
    vid = request.GET.get("vid", None)
    token = request.GET.get("token", None)
    if vid is None or token is None or vid == '' or token == '': raise Http404
    mvr = get_object_or_404(MailVertifySendRecord, id=vid)
    if mvr.token == token:
        if 'HTTP_X_FORWARDED_FOR' in request.META:
            ip = request.META['HTTP_X_FORWARDED_FOR']
        else:
            ip = request.META['REMOTE_ADDR']
        print('有用户点击了激活链接，ip:')
        print(ip)
        print("token", token)

        user_name = mvr.user_name
        email = mvr.email
        password = mvr.password
        inviter = mvr.who_inviter
        print(user_name, email)
        print("邀请者", inviter)
        # if len(User.objects.filter(username=user_name)) > 0: return HttpResponse("您已激活过账号")

        ips = AccountRegisterIpRecord.objects.filter(reg_date__date=timezone.datetime.today(),
                                                     ip=ip, action='active')
        print('此ip今日激活账号数量:%s' % len(ips))
        if len(ips) >= 1:
            return HttpResponse("何回もアカウントを作らないでください！")
        new_user_invite_code = get_unique_invite_code()

        u = User(username=user_name, email=email, invite_code=new_user_invite_code, inviter=inviter)
        u.set_password(password)
        if inviter is None:
            u.bandwidth_tmp = USER_BASE_BANDWIDTH
        else:
            u.bandwidth_tmp = INVITED_USER_BASE_BANDWIDTH
        u.save()
        mvr.password = ''
        mvr.save()
        login(request, u)
        r = AccountRegisterIpRecord(ip=ip, action='active')
        r.save()
        return HttpResponseRedirect('/')

    else:
        raise Http404


def account_reset_password(request):
    if request.method == 'POST':
        email = request.POST.get('email', None)
        if email is None: raise Http404
        try:
            validate_email(email)
        except ValidationError:
            return HttpResponse("email can't use")

        user = User.objects.filter(email=email)
        if len(user) == 0:
            return HttpResponse('email have no user')
        user = user[0]

        token = get_random_string(length=40)
        prmr = PasswordResetMailSendRecord(user=user, token=token)
        prmr.save()

        # 激活邮件
        reset_url = reverse('account:reset_password')
        host = request.get_host()
        reset_url = "http://" + host + reset_url + '?prmr=%d&token=%s' % (prmr.id, token)
        html_body = """
        <h1>KindleGalleryPusher：</h1>
        <p>%s</p>
        <p>下のリンクをクリックして、パスワードをリセットしてください。</p>
        <a href='%s'>リセット</a>
        <p></p>
        <p>%s</p>
        """ % (user.username, reset_url, reset_url)
        plain_body = """KindleGalleryPusherへ\n%s\n 下のリンクをクリックして、パスワードをリセットしてください。 %s""" % (user.username, reset_url)
        print("重置密码token:", reset_url)
        print("开始发送激活邮件...")
        send_mail('KindleGalleryPusherパスワードリセット - %s' % user.username,
                  plain_body,
                  settings.EMAIL_HOST_USER, [email], html_message=html_body, fail_silently=False)

        print("发送完毕")
        # login_res = login(request,new_user)
        # print("login res",login_res)
        return HttpResponse("ok")
    elif request.method == 'GET':
        return render(request, 'accounts/forgot.html')
    raise Http404


def rest_password(request):
    if request.method == "GET":
        prmr_id = request.GET.get('prmr', None)
        token = request.GET.get('token', None)
        if prmr_id is None or token is None or prmr_id == '' or token == '':
            raise Http404
        prmr_id = int(prmr_id)
        prmr = get_object_or_404(PasswordResetMailSendRecord, id=prmr_id)
        if prmr.used: return HttpResponse("此链接已经使用过！")
        if prmr.token == token:
            password = get_random_string(length=12)
            prmr.user.set_password(password)
            prmr.user.save()
            prmr.used = True
            prmr.save()

            return HttpResponse("您的新密码为：%s。\n请尽快更改密码" % (password))
        else:
            return HttpResponse("此链接无效！")

    else:
        raise Http404


def account_register(request: HttpRequest):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('main_site:home_page'))
        invite_code = request.GET.get('code', None)
        context = {"invite_code": invite_code}

        return render(request, 'accounts/register.html', context=context)
    elif request.method == 'POST':
        email = request.POST.get('email', "").strip()
        user_name = request.POST.get('username', '').strip()
        password = request.POST.get('password', "")
        invite_code = request.POST.get('invite_code', None)
        inviter = None
        if invite_code is not None:
            inviters = User.objects.filter(invite_code=invite_code)
            if len(inviters) > 0:
                inviter = inviters[0]

        # 获取用户的ip
        if 'HTTP_X_FORWARDED_FOR' in request.META:
            ip = request.META['HTTP_X_FORWARDED_FOR']
        else:
            ip = request.META['REMOTE_ADDR']
        print('有新用户发送注册邮件，ip:')
        print(ip)
        ips = AccountRegisterIpRecord.objects.filter(reg_date__date=timezone.datetime.today(),
                                                     ip=ip, action='mail')
        # ips = AccountRegisterIpRecord.objects.filter(ip=ip,date__date=timezone.datetime.date.today(),action='mail')

        print('此ip今日发送邮件数量%d' % len(ips))
        if len(ips) > 10:
            print('此地址今天请求发送邮件数量超过10封')
            return HttpResponse("mail over limit")

        if user_name == "":
            return HttpResponse("username can't use!")
        try:
            validate_email(user_name)
            return HttpResponse("don't use email as username")
        except ValidationError:
            pass
        if len(password) < 6:
            return HttpResponse("password too short!")
        if len(User.objects.filter(username=user_name)) > 0:
            return HttpResponse("same username already exits!")
        try:
            validate_email(email)
            if len(User.objects.filter(email=email)) > 0:
                return HttpResponse("email already used!")
        except ValidationError:
            return HttpResponse("email can't use")

        # new_user = User(username=user_name, password=password, email=email,is_active=False)
        # new_user.save()
        print("有新注册的账户: %s %s" % (user_name, email))
        token = get_random_string(length=40)
        mvr = MailVertifySendRecord(type='active', token=token, user_name=user_name, email=email, password=password,
                                    who_inviter=inviter)
        mvr.save()

        # 激活邮件
        active_url = reverse('account:active')
        host = request.get_host()
        active_url = "http://" + host + active_url + '?vid=%d&token=%s' % (mvr.id, token)
        html_body = """
        <p>KindleGalleryPusher</p>
        <p>%s</p>
        <p>KindleGalleryPusherへようこそ，下のリンクをクリックして、アカウントを有効にしてください。</p>
        <a href='%s'>アカウントを有効にする</a>
        <p></p>
        <p>%s</p>
        """ % (user_name, active_url, active_url)
        plain_body = """KindleGalleryPusher　\n%s\nKindleGalleryPusherへようこそ，下のリンクをクリックして、アカウントを有効にしてください: %s""" % (
        user_name, active_url)
        print("激活token:", active_url)
        print("开始发送激活邮件...")
        send_mail('KindleGalleryPusherへようこそ - %s' % user_name,
                  plain_body,
                  settings.EMAIL_HOST_USER, [email], html_message=html_body, fail_silently=False)

        print("发送完毕")
        ip_record = AccountRegisterIpRecord(action='mail', ip=ip)
        ip_record.save()
        # login_res = login(request,new_user)

account/templates/accounts/bandwidth_records.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KindleGalleryPusher {{ user.username }} データ使用量履歴</title>
    {% include 'mainsite/load_bootstrap.html' %}
</head>
<body>
{% include 'mainsite/book_info_header.html' %}
<div class="container">

    <div class="row" style="height: 4em;"></div>

    <div class="row"><h3>{{ user.username }} のデータ使用量履歴</h3></div>


    <div class="row">
        <table class="table table-hover table-sm">
            <thead>
            <tr>
                <th scope="col"></th>
                <th>写真集名</th>
                <th>アルバム</th>
                <th>ファイルサイズ(MB)</th>
                <th>消費前データ量(MB)</th>
                <th>消費後データ量(MB)</th>
                <th>消費時間</th>
                <th>タイプ</th>

            </tr>
            </thead>

            <tbody>
            {% for record in records %}
                <tr>
                    <td>{{ forloop.counter }} </td>
                    <td>{{ record.volume.book.title }}</td>
                    <td>{{ record.volume.name }}</td>
                    <td>{{ record.bandwidth_cost }}</td>
                    <td>{{ record.user_bandwidth_before }}</td>
                    <td>{{ record.user_bandwidth_after }}</td>
                    <td>{{ record.cost_date | date:'n月d日 Y年 G:i' }}</td>
                    <td> {{ record.action }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">ホームページ</a>
                </li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="?page=1" tabindex="-1"
                                                  aria-disabled="true">ホームページ</a></li>
            {% endif %}
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1"
                                         aria-disabled="true">前ページ</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">前ページ</a>
                </li>
            {% endif %}
            <li class="page-item"><a class="page-link active">{{ page.number }}</a></li>
            {% if page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">次ページ</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">次ページ</a></li>
            {% endif %}
            {% if page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">エンドページ</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">エンドページ</a></li>
            {% endif %}
        </ul>
    </nav>

</div>

</body>
</html>

account/templates/accounts/forgot.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>パスワードリセット - KindleGalleryPusher</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'mainsite/load_bootstrap.html' %}
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'account/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/main.css' %}">
    <!--===============================================================================================-->
    <script>

        onloginerror = function () {
            console.log("error");
        }

        function logto() {
            let error_box = document.getElementById('error-box');
            let ok_box = document.getElementById('reset-ok');
            message_box = document.getElementById("message-box");
            message_box_text = document.getElementById("message-box-txt");
            message_box.style.display = 'none';
            message_box_text.innerHTML = '';
            error_box.style.display = 'none';
            ok_box.style.display = 'none';

            let email = document.getElementById('email').value;
            let crsfsession = $("[name='csrfmiddlewaretoken']")[0].value;
            let postdata = `email=${email}&csrfmiddlewaretoken=${crsfsession}`;

            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onload = function (event) {
                if (xmlhttp.status == 200) {
                    message_box.style.display = 'block';
                    console.log("リセット成功しました");
                    ok_box.style.display = 'block';

                } else if (xmlhttp.status == 401) {
                    message_box.style.display = 'block';
                    document.getElementById('msg').style.display = 'none';
                    console.log("失敗しました");
                    error_box.style.display = 'block';
                }

            };
            xmlhttp.error = onloginerror;
            xmlhttp.open('post', "{% url 'account:forgot' %}");
            xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')
            xmlhttp.send(postdata);
            message_box_text.innerHTML = "リセットメールを送っています...";
            message_box.style.display = 'block';
        }
    </script>
</head>
<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url('{% static 'account/images/img-01.jpg' %}');">
        <div class="wrap-login100 p-t-190 p-b-30">
            <form id="login-form" class="login100-form validate-form" method="post" action="{% url 'account:login' %}">
                {% csrf_token %}
                <div class="login100-form-avatar">
                    <img src="{% static 'account/images/akkarin.png' %}" alt="AVATAR">
                </div>

                <span class="login100-form-title p-t-20 p-b-45">
						パスワードリセット
					</span>

                <div class="wrap-input100 validate-input m-b-10" data-validate="Username is required">
                    <input class="input100" id="email" type="text" name="email" placeholder="あなたのメールアドレス">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
                </div>

                <div class="container-login100-form-btn p-t-10">
                    <button class="login100-form-btn" onclick="logto()" type="button">
                        パスワードリセット
                    </button>
                </div>
                <div id="message-box" class="text-center w-full p-t-10 p-b-10" style="display: none">
                    <p id="message-box-txt" class="txt1 text-warning">

                    </p>
                </div>
                <div id="reset-error" class="text-center w-full p-t-10 p-b-10" style="display: none">
                    <p id='error-box' class="txt1 text-warning">
                    </p>
                </div>
                <div id="reset-ok" class="text-center w-full p-t-10 p-b-10" style="display: none">
                    <p class="txt1">
                        リセット終わりました、メールボックスを確認してください！
                    </p>
                    <p class="txt1">メールが迷惑ボックスに入る可能性があります</p>
                </div>
            </form>
        </div>
    </div>
</div>


<!--===============================================================================================-->
<script src="{% static 'account/vendor/bootstrap/js/popper.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account/js/main.js' %}"></script>

</body>
</html>

account/templates/accounts/kakin_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KindleGalleryPusher 充值</title>
</head>
<body>
<div class="container">
    <div class="row">
        <p>你好 {{ user.name }}, 您的订单id为: {{ order_id }}</p>
        <p> 付款后因到账需要一点时间，前耐心等待付款状态变更（2分钟内到账）</p>
        <p> 如5分钟内后流量依旧没有到账，请使用站内的问题反馈界面。并提供您上面的订单id和付款截图</p>
    </div>
    <div class="row">
        <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" allowfullscreen width="100%" height="1000px"
                    src="{{ order_url }}"></iframe>
        </div>
    </div>
</div>
</body>
</html>

account/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <title>登陆</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'mainsite/load_bootstrap.html' %}
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="{% static 'account/images/icons/favicon.ico' %}"/>
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css"
          href="{% static 'account/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/vendor/animate/animate.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/vendor/css-hamburgers/hamburgers.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/vendor/select2/select2.min.css' %}">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'account/css/main.css' %}">
    <!--===============================================================================================-->
    <script>

        onloginerror = function () {
            console.log("error");
        }

        function logto() {
            document.getElementById("login-error").style.display = 'none';
            document.getElementById('login-ok').style.display = 'none';

            let username = document.getElementById('username').value;
            let password = document.getElementById('password').value;
            let crsfsession = $("[name='csrfmiddlewaretoken']")[0].value;
            let postdata = `username=${username}&password=${password}&csrfmiddlewaretoken=${crsfsession}`;

            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onload = function (event) {
                if (xmlhttp.status == 200) {
                    console.log("ログイン成功しました");
                    document.getElementById("login-ok").style.display = 'block';
                    {% if redirect_path != None %}
                        setTimeout("location.href = '{{ redirect_path }}';", 1000);

                    {% else %}
                        setTimeout(" location.href = '/'", 1000);
                    {% endif %}

                } else if (xmlhttp.status == 401) {
                    console.log("ユーザー名あるいはパスワード正しくありません")
                    document.getElementById("login-error").style.display = 'block';
                }

            };
            xmlhttp.error = onloginerror;
            xmlhttp.open('post', "{% url 'account:login' %}");
            xmlhttp.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded')
            xmlhttp.send(postdata);
        }
    </script>
</head>
<body>

<div class="limiter">
    <div class="container-login100" style="background-image: url('{% static 'account/images/img-01.jpg' %}');">
        <div class="wrap-login100 p-t-190 p-b-30">
            <form id="login-form" class="login100-form validate-form" method="post" action="{% url 'account:login' %}">
                {% csrf_token %}
                <div class="login100-form-avatar">
                    <img src="{% static 'account/images/akkarin.png' %}" alt="AVATAR">
                </div>

                <span class="login100-form-title p-t-20 p-b-45">
						ログイン
					</span>

                <div class="wrap-input100 validate-input m-b-10" data-validate="Username is required">
                    <input class="input100" id="username" type="text" name="username" placeholder="ユーザー名あるいはメールアドレス">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-user"></i>
						</span>
                </div>

                <div class="wrap-input100 validate-input m-b-10" data-validate="Password is required">
                    <input class="input100" id="password" type="password" name="password" placeholder="密码">
                    <span class="focus-input100"></span>
                    <span class="symbol-input100">
							<i class="fa fa-lock"></i>
						</span>
                </div>

                <div class="container-login100-form-btn p-t-10">
                    <button class="login100-form-btn" onclick="logto()" type="button">
                        ログイン
                    </button>
                </div>
                <div id="login-error" class="text-center w-full p-t-10 p-b-10" style="display: none">
                    <p class="txt1 text-warning">
                        ログイン失敗しました！
                    </p>
                </div>
                <div id="login-ok" class="text-center w-full p-t-10 p-b-10" style="display: none">
                    <p class="txt1">
                        ログイン成功！ 1s後ホームページに戻ります！
                    </p>
                </div>
                <div class="text-center w-full p-t-25 p-b-20">
                    <a href="{% url 'account:forgot' %}" class="txt1">
                        パスワードリセット？
                    </a>
                </div>

                <div class="text-center w-full">
                    <a class="txt1" href="{% url 'account:register' %}">
                        アカウント登録
                        <i class="fa fa-long-arrow-right"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>


<!--===============================================================================================-->
<script src="{% static 'account/vendor/bootstrap/js/popper.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'account/js/main.js' %}"></script>

</body>
</html>

account/templates/accounts/precharge.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KindleGalleryPusher 捐赠Vip</title>
    {% include 'mainsite/load_bootstrap.html' %}
</head>
<body>
{% include 'mainsite/book_info_header.html' %}
<div class="container">

    <div class="row" style="height: 4em;"></div>
    {% if is_global %}
        <div class="row"><h3>捐赠套餐</h3></div>
    {% else %}
        <div class="row"><h3></h3></div>
    {% endif %}


    <div class="row">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">套餐一(1个月)</h5>
                <h6 class="card-subtitle mb-2 text-muted">20¥</h6>
                <p class="card-text">捐赠后您将成为Vip会员，获得20GB流量</p>
                <p class="card-text">推送不消耗流量</p>
                <a href="{% url 'account:charge' %}?mode=vip" class="card-link">捐赠</a>
            </div>
        </div>
    </div>

</div>

</body>
</html>