KindleGalleryPusher/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from mainsite.views import home_page, volume_download, show_bandwidth_rule, feedback
from ebookconvert.views import convert_queue
from django.conf import settings
from django.conf.urls import include, url  # For django versions before 2.0
from django.urls import include, path  # For django versions from 2.0 and up

urlpatterns = [
                  path("", home_page, name='home_page'),
                  path('rule/', show_bandwidth_rule, name='bandwidth_rule'),
                  path("book/", include("mainsite.urls")),
                  path("feedback/", feedback, name='feedback'),
                  path("download/", volume_download, name='volume_download'),
                  path('accounts/', include('account.urls')),
                  path('search/', include('mainsite.urls_search')),
                  path('pushtask/', include('pushmonitor.urls')),
                  path('converts/', convert_queue, name='convert_queue'),
                  path('admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path('login/', views.account_login, name='login'),
    path('register/', views.account_register, name='register'),
    path('forgot/', views.account_reset_password, name='forgot'),
    path('resetpsw/', views.rest_password, name='reset_password'),
    path('active/', views.account_activate, name='active'),
    path('logout/', views.account_logout, name='logout'),
    path('user/', views.set_self_account, name='self_profile'),
    path('user/profile', views.set_profile, name='set_profile'),
    path('user/<int:uid>/', views.account_profile, name='other_profile'),
    path('user/queue/', views.push_queue, name='push_queue'),
    path('charge/', views.kakin, name='charge'),
    path('payoknDxx4S0qCf/', views.payok, name='pay_ok'),
    path('precharge/', views.precharge, name='precharge'),
    path('records/', views.bandwidth_cost_records, name='bandwidth_records'),
    path('collections/', views.full_collection, name='collections'),
    path('subscs/', views.full_subscs, name='subscs'),

]

mainsite/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'main_site'
urlpatterns = [
    path('', views.home_page, name='home_page'),
    path("<int:book_id>/", views.book_info, name="book"),
    path("<int:book_id>/subsc/", views.book_subscribe, name='book_subscribe'),
    path("<int:book_id>/collect/", views.book_collect, name='book_collect'),
    path("<int:book_id>/comment/", views.book_comment, name='book_comment'),
    path("<int:book_id>/score/", views.book_score, name='book_score'),
    path("<int:book_id>/push/", views.book_push, name='book_push'),
    path("<int:book_id>/upload/", views.upload_file, name='book_upload'),
    path("recently/", views.full_recently_updated_books, name='book_recently'),
]

mainsite/views.py
import re
import time
from urllib.parse import quote, urlencode

from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.utils.timezone import now, timedelta

from django.shortcuts import render
from django.http import HttpResponse, Http404, JsonResponse, StreamingHttpResponse, FileResponse
# Create your views here.
from . import tools
from django.views.decorators.csrf import csrf_exempt
import json
from .models import *
from django.shortcuts import get_object_or_404, render
from .tools import get_hash_filename
import itertools
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from account.models import *
from pushmonitor.models import put_task_to_push_queue

DOWNLOAD_LINK_AVAILABLE_HOURS = 1


def home_page(request):
    homepage_book_groups = HomePageGroup.objects.all()
    side_special = HomePageSpecialSide.objects.all()
    recent_updated = Book.objects.filter(show=True).order_by('-update_time')[:18]

    context = {"homepage_book_groups": homepage_book_groups,
               "recent_updated": recent_updated,
               "side_special": side_special}
    return render(request, 'mainsite/homepage.html', context=context)


def full_recently_updated_books(request):
    page_idx = request.GET.get("page", 1)
    recent_updated = Book.objects.filter(show=True).order_by('-update_time')
    recent_updated_pages = Paginator(recent_updated, 20)
    page = recent_updated_pages.get_page(page_idx)

    context = {"page": page,
               "title": '最近更新的漫画列表'}
    return render(request, 'mainsite/book_list.html', context=context)


def search_page(request):
    if request.method != 'GET':
        raise Http404

    keyword = request.GET.get("keyword", None)  # type:str
    author = request.GET.get("author", None)  # type:str
    catalog = request.GET.get("catalog", None)
    tag = request.GET.get("tag", None)
    # keywords = keyword.split(' ')
    if keyword is None and author is None:
        books = []
        keyword = ""
    elif author is None and keyword is not None:
        books = Book.objects.filter(title__contains=keyword)
        keyword = keyword
    elif author is not None and keyword is None:
        books = Book.objects.filter(author__name__contains=author)
        keyword = "作者 %s" % (author)
    elif author is not None and keyword is not None:
        books = Book.objects.filter(author__name__contains=author, title__contains=keyword)
        keyword = "%s %s" % (keyword, author)

    if catalog is not None:
        books = Book.objects.filter(tags__name__contains=catalog, tags__group='catalog')
        keyword = "分类 %s" % (catalog)
    if tag is not None:
        books = Book.objects.filter(tags__name__contains=tag, tags__group__isnull=True)
        keyword = "标签 %s" % (tag)
    context = {"books": books,
               "keyword": keyword}
    return render(request, 'mainsite/search_res.html', context=context)


def book_info(request, book_id):
    book = get_object_or_404(Book, id=book_id)  # type:Book

    user = request.user

    cover_id = book.cover_id
    try:
        cover_image = ImageWithThumb.objects.get(id=cover_id)
    except ImageWithThumb.DoesNotExist:
        # TODO: 没有图片的时候，显示默认的封面
        cover_image = False

    volumes_dict = {}
    volumes = Volume.objects.filter(book=book_id, show=True)
    type_list = itertools.groupby(volumes.values_list('type__name', flat=True))

    # values_list
    for type_string, iter in type_list:
        v = Volume.objects.filter(book=book_id, show=True, type__name=type_string).order_by('index')
        volumes_dict[type_string] = v
    context = {"book": book,
               "cover_image": cover_image,
               "volumes_dict": volumes_dict,
               "user": user}
    print(volumes_dict)

    return render(request, 'mainsite/book_info.html', context)


@login_required()
def book_subscribe(request, book_id):
    if request.method == "GET":
        # TODO: 如果今后有时间的话，可以搞个获取订阅者列表的接口
        raise Http404
    elif request.method == "POST":
        user = request.user  # type:User
        if len(user.subscriptes.filter(id=book_id)) == 0:
            book = get_object_or_404(Book, id=book_id)
            user.subscriptes.add(book)
            user.save()
            return HttpResponse("ok")
    elif request.method == "DELETE":
        user = request.user  # type:User
        if len(user.subscriptes.filter(id=book_id)) > 0:
            book = get_object_or_404(Book, id=book_id)
            user.subscriptes.remove(book)
            user.save()
            return HttpResponse("ok")
    raise Http404


@login_required()
def book_collect(request, book_id):
    if request.method == "GET":
        # TODO: 如果今后有时间的话，可以搞个获取收藏者列表的接口
        raise Http404
    elif request.method == "POST":
        user = request.user  # type:User
        if len(user.collections.filter(id=book_id)) == 0:
            book = get_object_or_404(Book, id=book_id)
            user.collections.add(book)
            user.save()
            return HttpResponse("ok")
    elif request.method == "DELETE":
        user = request.user  # type:User
        if len(user.collections.filter(id=book_id)) > 0:
            book = get_object_or_404(Book, id=book_id)
            user.collections.remove(book)
            user.save()
            return HttpResponse("ok")
    raise Http404


@login_required()
def book_comment(request, book_id):
    if request.method == "GET":
        # TODO: 如果今后有时间的话，可以搞个获取书籍评论列表的功能
        raise Http404
    elif request.method == "POST":
        user = request.user  # type:User
        message = request.POST.get("message", None)  # type:str
        if message is not None and (message.replace(" ", "").replace("　", "") != ""):
            book = get_object_or_404(Book, id=book_id)
            comment = Comment(book=book, user=user, message=message)
            comment.save()
            return HttpResponse("ok")
    raise Http404


@login_required()
def book_score(request, book_id):
    if request.method == "GET":
        # TODO: 如果今后有时间的话，可以搞个获取书籍评论列表的功能
        raise Http404
    elif request.method == "POST":
        book = get_object_or_404(Book, id=book_id)
        user = request.user  # type:User
        score = request.POST.get("score", "")
        try:
            score = int(score)
        except ValueError:
            raise Http404
        if score < 1: score = 1
        if score > 5: score = 5

        query = Score.objects.filter(user=user, book=book)
        if len(query) > 0:
            score_obj = query[0]
            score_obj.score = score
        else:
            score_obj = Score(score=score, book=book, user=user)
        score_obj.save()
        return HttpResponse("ok")
    raise Http404


@login_required()
def book_push(request, book_id):
    if request.method == "POST":
        volume_id = request.POST.get("volume_id", None)
        force_push = request.POST.get("fore_push", False)
        if force_push == 'true':
            force_push = True
        else:
            force_push = False
        if volume_id is None: raise Http404
        book = get_object_or_404(Book, id=book_id)
        volume = get_object_or_404(Volume, id=volume_id)
        user = request.user
        push_res = put_task_to_push_queue(user, volume, force_push)
        if push_res == 'pending':
            return HttpResponse("Already in queue!")
        if push_res == 'doing':
            return HttpResponse("Now in pushing!")
        if push_res == 'done':
            return HttpResponse("Have pushed before!")
        if push_res == 'bandwidth less':
            return HttpResponse("bandwidth less!")
        if push_res == 'no kindle email':
            return HttpResponse("No kindle email!")
        if push_res == 'ok':
            return HttpResponse("ok")
    raise Http404


@login_required()
def volume_download(request):
    if request.method == 'GET':
        user = request.user
        volume_id = int(request.GET.get('volume_id', ''))
        type = request.GET.get('type', '')
        volume = get_object_or_404(Volume, id=volume_id)
        # 虽然名叫add，但实际上如果指定时间之内已经下载过的话的，并不会消费流量，True为可以提供下载
        # False为不能下载，得POST后再下
        res = user.have_cost_bandwidth_recently(volume)
        if res:
            file = None
            if type == 'zip':
                file = volume.zip_file
            elif type == 'mobi':
                file = volume.mobi_file
            elif type == 'mobi_push':
                file = volume.mobi_push_file
            elif type == 'epub':
                file = volume.epub_file
            else:
                raise Http404
            file_body, file_ext = os.path.splitext(file.name)
            attachment_filename = "[%s] %s %s%s" % (volume.book.get_authors_string(),
                                                    volume.book.title,
                                                    volume.name,
                                                    file_ext)
            print("附件名称:", attachment_filename)

            response = HttpResponse()
            try:
                attachment_filename.encode('ascii')
                file_expr = 'filename="{}"'.format(attachment_filename)
            except UnicodeEncodeError:
                file_expr = "filename*=utf-8''{}".format(quote(attachment_filename))
            response['Content-Disposition'] = 'attachment; {}'.format(file_expr)
            # response['Content-Type'] = 'application/octet-stream'
            # response['Content-Length'] = file.size
            file_path_url = quote(file.name)
            print(file_path_url)
            response['X-Accel-Redirect'] = '/donwloadbook/%s' % file_path_url
            print("X-ACCEL:", response['X-Accel-Redirect'])
            # response['Content-Type'] = 'application/octet-stream'
            # response['Content-Disposition'] = 'attachment;filename="%s"' %  attachment_filename

            return response
        else:
            raise Http404

mainsite/templates/mainsite/admin_covers.html
<input type="file" name="uploaded_image"/>
<div style="overflow-x:auto;white-space: nowrap;width: 600px;">
    <script>
        document.getElementById("book_form").setAttribute("enctype", "multipart/form-data")
    </script>

    {% for cover in covers %}
        <div style="display: inline-block;;margin: 5px;width: 100px;height: 100%;">
            <div style="text-align: center"><p>{{ cover.id }}</p></div>
            <div><img src="{{ cover.thumb_image.url }}" style="width: 100px"></div>

            <div align="center"><input type="radio"
                    {% if cover.id == cover_id %}
                                       checked="checked"
                    {% endif %}
                                       id="{{ cover.id }}" name="cover_select_radio" value="{{ cover.id }}"></div>
        </div>
    {% endfor %}
</div>

mainsite/templates/mainsite/book_info_header.html
{% load static %}
<script>
    function activate_tab_and_go_to(panel_id) {
        $(`#tab-files a[href='#${panel_id}']`).tab('show');
        location.href = "#tab-files";
    }

    function activate_self(li) {
        console.log("nav clicked");
        console.log(this);
        document.getElementById("header-nav").getElementsByClassName("active")[0].classList.remove("active")
        li.classList.add("active");
    }

    function logout() {
        logout_form = document.getElementById("logout");
        logout_form.submit();
    }
</script>

<nav class="navbar navbar-expand-sm fixed-top bg-light" role="navigation">

    <a class="navbar-brand" href="/">
        <img src="{% static 'mainsite/logo.png' %}" width="30" height="30"
             class="d-inline-block align-top" alt="">
        KindleGalleryPusher
    </a>


    <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse  justify-content-end" id="collapsibleNavbar">
        {% if book %}
            <ul class="nav nav-tabs" id="header-nav">
                <li onclick="activate_self(this)" class="nav-item">
                    <a class="active nav-link" href="#top">Top</a>
                </li>
                <li onclick="activate_self(this)" class="nav-item">
                    <a class="nav-link" href="#panel-mobi" onclick="activate_tab_and_go_to('panel-mobi')">Mobi</a>
                </li>
                <li onclick="activate_self(this)" class="nav-item">
                    <a class="nav-link" href="#panel-epub" onclick="activate_tab_and_go_to('panel-epub')">Epub</a>
                </li>

            </ul>
        {% endif %}
        <form class="form-inline" style="max-width: 400px; margin-right: 2em" role="search"
              action="{% url 'search_site:search_page' %}" method="get">
            <input type="text" style="width: 200px;" name="keyword" class="form-control mr-sm-2" placeholder="写真集名"/>
            <button type="submit" class="btn btn-outline-primary my-2 my-sm-0">検索</button>
        </form>

        {% if user.id is None %}
            <div style="display: inline-flex;">
                <a class="navbar-brand right-auto" href="#"><img src="{% static 'account/images/akkarin.png' %}"
                                                                 class="d-inline-block align-top rounded-circle"
                                                                 style="width:30px;height: 30px"></a>
                <ul class="navbar-nav right-auto">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            游客
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'account:login' %}">ログイン</a>
                            <a class="dropdown-item" href="{% url 'account:register' %}">登録</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'feedback' %}">Feedback</a>
                        </div>
                    </li>
                </ul>
            </div>
        {% else %}
            <div style="display: inline-flex;">
                {% if user.avatar %}

                    <a class="navbar-brand right-auto" href="{% url 'account:self_profile' %}"><img
                            src="{{ user.avatar.normal_image.url }}" class="d-inline-block align-top rounded-circle"
                            style="width:30px;height: 30px"></a>
                {% else %}
                    <a class="navbar-brand right-auto" href="{% url 'account:self_profile' %}"><img
                            src="{% static 'account/images/akkarin.png' %}"
                            class="d-inline-block align-top rounded-circle" style="width:30px;height: 30px"></a>
                {% endif %}
                <ul class="navbar-nav right-auto justify-content-end">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu  dropdown-menu-lg-right" aria-labelledby="navbarDropdownMenuLink">
                            <div class="dropdown-item"><p>
                                残り: {{ user.bandwidth_remain }}MB/{{ user.get_bandwidth_total }}MB</p></div>
                            <div class="progress" style="margin-left: 20px;margin-right: 20px">
                                <div class="progress-bar bg-info" role="progressbar"
                                     style="width: {{ user.bandwidth_percent }}%" aria-valuenow="50" aria-valuemin="0"
                                     aria-valuemax="100">残り{{ user.bandwidth_remain }}MB
                                </div>
                            </div>

                            {% if user.username == 'admin' %}
                                <div class="dropdown-divider"></div>

                                <a class="dropdown-item" href="{% url 'convert_queue' %}?global=1">Convert隊列</a>
                                <a class="dropdown-item" href="/admin">サイト管理</a>

                            {% endif %}
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'account:push_queue' %}">プッシュ隊列</a>
                            <a class="dropdown-item" href="{% url 'account:bandwidth_records' %}">データ量消費履歴</a>
                            <a class="dropdown-item" href="{% url 'account:self_profile' %}">個人情報</a>


                            <form id="logout" method="post" action="{% url 'account:logout' %}">
                                {% csrf_token %}
                                <a class="dropdown-item" href="#" onclick="logout()">ロゴアウト</a>

                            </form>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="{% url 'feedback' %}">Feedback</a>
                        </div>
                    </li>
                </ul>
            </div>
        {% endif %}


    </div>

</nav>

mainsite/templates/mainsite/book_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KindleGalleryPusher - 写真集</title>
    {% include 'mainsite/load_bootstrap.html' %}
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
    </style>
    <style>
        .myp {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            margin-bottom: 2px;
        }

        book-title {

        }
    </style>
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })

    </script>
    <style>
        .head-div {
            border-bottom: 1px solid #dddddd;
            margin-bottom: 10px
        }
    </style>
</head>
<body>
{% include 'mainsite/book_info_header.html' %}
<div style="height: 5em;"></div>
<div class="container">
    <div class="row">
        <div class="col-12">

            <div class="row">
                <div class="col-12">
                    <div class="head-div"><h4><span>{{ title }}</span></h4></div>
                </div>
            </div>
            <div class="row" style="padding: 7px; margin-bottom: 2em">
                {% for book in page %}
                    <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2 col-4 book-info"
                         style="width: 100px; margin-bottom: 1em">
                        <a href="{% url 'main_site:book' book_id=book.id %}" data-toggle="popover"
                           data-placement="right" data-container="{{ book.desc }}" data-title="{{ book.title }}">
                            <img src="{{ book.cover_used.thumb_image.url }}" width="100" class="rounded img-responsive"></a>
                        <div style="width: 100px;text-align: center;margin: 4px;font-size: 0.7em;"><a
                                style="margin-bottom: 2px" href="/book/{{ book.id }}"><p
                                class="myp"> {{ book.title }}</p></a></div>
                        <div style="width: 100px;text-align: center"><p class="myp">
                            {{ book.get_newest_volume.name }}
                        </p></div>

                    </div>

                {% endfor %}
            </div>

        </div>
    </div>
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">首页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="?page=1" tabindex="-1"
                                                  aria-disabled="true">首页</a></li>
            {% endif %}
            {% if page.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}" tabindex="-1"
                                         aria-disabled="true">上一页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">上一页</a>
                </li>
            {% endif %}
            <li class="page-item"><a class="page-link active">{{ page.number }}</a></li>
            {% if page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">下一页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">下一页</a></li>
            {% endif %}
            {% if page.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">尾页</a></li>
            {% else %}
                <li class="page-item disabled"><a class="page-link" href="#">尾页</a></li>
            {% endif %}
        </ul>
    </nav>


</div>


</body>
</html>

mainsite/templates/mainsite/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KindleGalleryPusher Feedback</title>
    {% include 'mainsite/load_bootstrap.html' %}
</head>
<body>
<div class="container">
    {% include 'mainsite/book_info_header.html' %}
    <div style="height: 4em;"></div>
    <div class="row clearfix">
        <div class="col-md-12 column">
            <form role="form" id="feedback-form" method="post" action="{% url 'feedback' %}">

                <div class="form-group">
                    <label for="exampleInputEmail1">貴方のメールアドレス</label><input type="text" class="form-control"
                                                                             name="email"/>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">問題</label><textarea rows="10" class="form-control" name="message"
                                                                        id="message" form="feedback-form"
                                                                        placeholder="問題"/></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Feedback送り</button>

            </form>
        </div>
    </div>
</div>
</body>
</html>

mainsite/templates/mainsite/homepage.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>KindleGalleryPusher　-　貴方の写真集をみんなとシェアしませんか？</title>
    {% include 'mainsite/load_bootstrap.html' %}
    <style>
        /* Make the image fully responsive */
        .carousel-inner img {
            width: 100%;
            height: 100%;
        }
    </style>
    <style>
        .myp {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            margin-bottom: 2px;
        }

        book-title {

        }
    </style>
    <script>
        $(function () {
            $('[data-toggle="popover"]').popover()
        })

    </script>
    <style>
        .head-div {
            border-bottom: 1px solid #dddddd;
            margin-bottom: 10px
        }
    </style>
</head>
<body>
{% include 'mainsite/book_info_header.html' %}
<div style="height: 5em;"></div>
<div class="container">
    <div class="row">
        <div class="col-sm-12 col-xs-12 col-md-10 col-lg-10">

            <div class="row">
                <div class="col-12">
                    <div class="head-div" style="display:inline-block"><h4><span><a
                            href="{% url 'main_site:book_recently' %}">最新写真集</a></span></h4></div>
                </div>
            </div>
            <div class="row" style="padding: 7px; margin-bottom: 2em">
                {% for book in recent_updated %}
                    <div class="col-xs-4 col-sm-4 col-md-2 col-lg-2 col-4 book-info"
                         style="width: 100px; margin-bottom: 1em">
                        <a href="{% url 'main_site:book' book_id=book.id %}" data-toggle="popover"
                           data-placement="right" data-container="{{ book.desc }}" data-title="{{ book.title }}">
                            <img src="{{ book.cover_used.thumb_image.url }}" width="100" class="rounded img-responsive"></a>
                        <div style="width: 100px;text-align: center;margin: 4px;font-size: 0.7em;"><a
                                style="margin-bottom: 2px" href="/book/{{ book.id }}"><p
                                class="myp"> {{ book.title }}</p></a></div>
                        <div style="width: 100px;text-align: center"><p class="myp">
                            {{ book.get_newest_volume.name }}
                        </p></div>

                    </div>

                {% endfor %}
            </div>
            {% for group in homepage_book_groups %}
                <div class="row head-div">
                    <div class="col-12"><h4>{{ group.name }}</h4></div>
                </div>
                <div class="row" style='text-align: center; margin-bottom: 2em'>
                    {% for book in group.books.all %}
                        <div class="col-xs-4 col-sm-3 col-md-2 col-lg-2 col-4 book-info" style="width: 50px;">
                            <div><a href="{% url 'main_site:book' book_id=book.id %}"><img
                                    src="{{ book.cover_used.thumb_image.url }}" width="100"
                                    class="rounded img-responsive"></a></div>
                            <div><a href="/book/{{ book.id }}"><p class="myp"
                                                                  style="text-overflow:ellipsis"> {{ book.title }}</p>
                            </a></div>
                            <div><p class="myp">
                                {% for author in book.author.all %}
                                    {{ author.name }}&ensp;
                                {% endfor %}</p></div>
                        </div>

                    {% endfor %}
                </div>


            {% endfor %}
        </div>
        <div class="col-md-2 col-lg-2 hidden-xs hidden-sm">
            <h4>すすめ</h4>

            {% for b in side_special %}
                <img src="{{ b.book.cover_used.thumb_image.url }}">
                <p class="myp"><a href="/book/{{ b.book.id }}">{{ b.book.title }}</a></p>
                <p style="text-overflow:ellipsis">{{ b.desc }}</p>

            {% endfor %}
        </div>

    </div>

</div>


</body>
</html>

mainsite/templates/mainsite/upload_by_localfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>从服务器本地上传</title>
</head>
<body>
<form method="post" action="{% url 'main_site:book_upload' book.id %}">
    {% csrf_token %}
    <input name="path" id="path" style="width: 500px;" type="text">
    <input name="action" value="show" hidden>
    <input type="submit">
</form>
</body>
</html>

mainsite/templates/mainsite/upload_by_localfile_show_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>从服务器本地上传</title>
</head>
<body>
<form method="post" action="{% url 'main_site:book_upload' book.id %}">
    {% csrf_token %}
    {% for file in files %}
        <div>{{ file.0 }}<input name="{{ file.1 }}" value="{{ file.1 }}"></div>
    {% endfor %}
    <input name="path" id="path" type="text" value="{{ path }}">
    <input name="action" value="set" hidden>
    <input type="submit">
</form>
</body>
</html>